# Generated by Django 6.0.3 on 2026-04-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BridgeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('span_length_m', models.DecimalField(decimal_places=3, max_digits=8)),
                ('dead_load_kN_per_m', models.DecimalField(decimal_places=3, max_digits=8)),
                ('point_load_kN', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('load_position_m', models.DecimalField(decimal_places=3, max_digits=8)),
                ('impact_factor', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('E_GPa', models.DecimalField(decimal_places=3, default=200, max_digits=8)),
                ('section_y_m', models.DecimalField(decimal_places=3, default=0.2, max_digits=8)),
                ('I_m4', models.DecimalField(decimal_places=8, max_digits=12)),
                ('steel_grade', models.CharField(choices=[('Fe250', 'Fe250'), ('Fe350', 'Fe350'), ('Fe415', 'Fe415'), ('Fe500', 'Fe500'), ('Fe550', 'Fe550')], max_length=10)),
                ('n_points', models.PositiveSmallIntegerField(default=99)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
