# Generated by Django 6.0.3 on 2026-04-08 20:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BridgeAnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('span_length', models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(200.0)])),
                ('support_condition', models.CharField(choices=[('simply_supported', 'Simply Supported'), ('continuous', 'Continuous'), ('fixed', 'Fixed-Fixed'), ('pinned_roller', 'Pinned-Roller')], default='simply_supported', max_length=20)),
                ('dead_load', models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(500.0)])),
                ('point_load', models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('load_position', models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('load_class', models.CharField(choices=[('IRC_AA', 'IRC Class AA'), ('IRC_A', 'IRC Class A'), ('IRC_70R', 'IRC Class 70R'), ('IRC_SV', 'IRC Class SV'), ('pedestrian', 'Pedestrian'), ('custom', 'Custom (manual entry)')], default='custom', max_length=20)),
                ('impact_factor', models.DecimalField(decimal_places=3, default=0.1, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.5)])),
                ('steel_grade', models.CharField(choices=[('Fe250', 'Fe250 (fy=250 MPa)'), ('Fe350', 'Fe350 (fy=350 MPa)'), ('Fe415', 'Fe415 (fy=415 MPa)'), ('Fe500', 'Fe500 (fy=500 MPa)'), ('Fe550', 'Fe550 (fy=550 MPa)')], default='Fe415', max_length=10)),
                ('youngs_modulus', models.DecimalField(decimal_places=3, help_text='GPa - allowed within +-5% of 200 GPa per IS 800', max_digits=8, validators=[django.core.validators.MinValueValidator(190.0), django.core.validators.MaxValueValidator(210.0)])),
                ('moment_of_inertia', models.DecimalField(decimal_places=8, help_text='m^4', max_digits=12, validators=[django.core.validators.MinValueValidator(1e-08), django.core.validators.MaxValueValidator(1.0)])),
                ('section_y', models.DecimalField(decimal_places=4, help_text='Distance from neutral axis to extreme fiber (m)', max_digits=8, validators=[django.core.validators.MinValueValidator(0.0001)])),
                ('plot_points', models.IntegerField(default=99, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)])),
                ('max_shear_force', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('max_bending_moment', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('max_deflection', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('max_normal_stress', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('max_shear_stress', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('reaction_a', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('reaction_b', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('stress_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('deflection_ratio', models.CharField(blank=True, max_length=20, null=True)),
                ('plot_data', models.JSONField(blank=True, null=True)),
                ('compliance_status', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('WARNING', 'Warning'), ('PENDING', 'Pending')], db_index=True, default='PENDING', max_length=10)),
                ('report_generated', models.BooleanField(default=False)),
                ('report_path', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'bridge_analysis_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeComplianceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('clause', models.CharField(choices=[('IS800_Cl5.6.1', 'IS 800 Cl.5.6.1 - Deflection'), ('IS800_Cl8.2', 'IS 800 Cl.8.2 - Bending'), ('IS800_Cl8.4', 'IS 800 Cl.8.4 - Shear Stress'), ('IS456_Cl23.2', 'IS 456 Cl.23.2 - Deflection (concrete)'), ('IRC_Cl204', 'IRC Cl.204 - Live load')], db_index=True, max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('computed', models.DecimalField(decimal_places=6, max_digits=12)),
                ('limit', models.DecimalField(decimal_places=6, max_digits=12)),
                ('unit', models.CharField(max_length=20)),
                ('result', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('WARNING', 'Warning'), ('PENDING', 'Pending')], db_index=True, max_length=10)),
            ],
            options={
                'db_table': 'code_compliance_check',
            },
        ),
        migrations.CreateModel(
            name='SteelSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('designation', models.CharField(db_index=True, max_length=30, unique=True)),
                ('moment_of_inertia', models.DecimalField(decimal_places=8, help_text='m^4', max_digits=12)),
                ('section_modulus', models.DecimalField(decimal_places=8, help_text='m^3', max_digits=12)),
                ('cross_section_area', models.DecimalField(decimal_places=6, help_text='m^2', max_digits=10)),
                ('depth', models.DecimalField(decimal_places=4, help_text='m', max_digits=8)),
                ('flange_width', models.DecimalField(decimal_places=4, help_text='m', max_digits=8)),
                ('web_thickness', models.DecimalField(decimal_places=4, help_text='m', max_digits=8)),
                ('steel_grade', models.CharField(choices=[('Fe250', 'Fe250 (fy=250 MPa)'), ('Fe350', 'Fe350 (fy=350 MPa)'), ('Fe415', 'Fe415 (fy=415 MPa)'), ('Fe500', 'Fe500 (fy=500 MPa)'), ('Fe550', 'Fe550 (fy=550 MPa)')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'steel_section',
                'ordering': ['designation'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('case_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('description', models.CharField(max_length=300)),
                ('suite_name', models.CharField(db_index=True, max_length=100)),
                ('span_length', models.DecimalField(decimal_places=3, max_digits=8)),
                ('dead_load', models.DecimalField(decimal_places=3, max_digits=8)),
                ('point_load', models.DecimalField(decimal_places=3, max_digits=8)),
                ('load_position', models.DecimalField(decimal_places=3, max_digits=8)),
                ('moment_of_inertia', models.DecimalField(decimal_places=8, max_digits=12)),
                ('youngs_modulus', models.DecimalField(decimal_places=3, max_digits=8)),
                ('steel_grade', models.CharField(choices=[('Fe250', 'Fe250 (fy=250 MPa)'), ('Fe350', 'Fe350 (fy=350 MPa)'), ('Fe415', 'Fe415 (fy=415 MPa)'), ('Fe500', 'Fe500 (fy=500 MPa)'), ('Fe550', 'Fe550 (fy=550 MPa)')], max_length=10)),
                ('section_y', models.DecimalField(decimal_places=4, max_digits=8)),
                ('expected_max_shear', models.DecimalField(decimal_places=4, max_digits=10)),
                ('expected_max_moment', models.DecimalField(decimal_places=4, max_digits=10)),
                ('expected_max_deflection', models.DecimalField(decimal_places=6, max_digits=10)),
                ('expected_max_stress', models.DecimalField(decimal_places=4, max_digits=10)),
                ('expected_reaction_a', models.DecimalField(decimal_places=4, max_digits=10)),
                ('expected_reaction_b', models.DecimalField(decimal_places=4, max_digits=10)),
                ('tol_shear', models.DecimalField(decimal_places=4, default=0.01, max_digits=8)),
                ('tol_moment', models.DecimalField(decimal_places=4, default=0.05, max_digits=8)),
                ('tol_deflection', models.DecimalField(decimal_places=6, default=0.001, max_digits=8)),
                ('tol_stress', models.DecimalField(decimal_places=4, default=0.1, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'test_case',
                'ordering': ['suite_name', 'case_id'],
            },
        ),
        migrations.CreateModel(
            name='ValidationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('suite_name', models.CharField(db_index=True, max_length=100)),
                ('triggered_by', models.CharField(choices=[('api', 'API'), ('ci', 'GitHub Actions'), ('manual', 'Manual')], default='api', max_length=20)),
                ('total_cases', models.IntegerField(default=0)),
                ('passed', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('pass_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('results_payload', models.JSONField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'validation_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='BridgeAnalysis',
        ),
        migrations.AddIndex(
            model_name='bridgeanalysisrun',
            index=models.Index(fields=['compliance_status', 'created_at'], name='bridge_anal_complia_5376f0_idx'),
        ),
        migrations.AddIndex(
            model_name='bridgeanalysisrun',
            index=models.Index(fields=['steel_grade', 'span_length'], name='bridge_anal_steel_g_123fe8_idx'),
        ),
        migrations.AddField(
            model_name='codecompliancecheck',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_checks', to='api.bridgeanalysisrun'),
        ),
        migrations.AlterUniqueTogether(
            name='codecompliancecheck',
            unique_together={('run', 'clause')},
        ),
    ]
